from PIL.Image import Image

class PdfiumError(Exception): ...

class PdfBitmap:
    def to_pil(self) -> Image: ...
    def close(self) -> None: ...

class PdfPage:
    def render(self, *, scale: float, grayscale: bool) -> PdfBitmap: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input: bytes) -> None: ...
    def __len__(self) -> int: ...
    def get_page(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
